package:
  name: netcdf_info
  version: "0.0.1"

source:
  git_url: https://github.com/Alanamosse/Galaxy-E/tree/master/tools/read_netcdf/conda-test.git

build:
  number: 0

requirements:
  build:
    -  libnetcdf
    -  gcc
  run:
    -  libgcc

